#!/bin/bash

if [ "$EUID" -ne 0 ]; then
  echo "ERROR: run with sudo"
  exit 1
fi

# Replace frank with your username
ip tuntap add dev tap0 mode tap user frank
ip addr add 192.168.7.1/24 dev tap0
ip link set tap0 up
